import { type Kysely, sql } from "kysely";

/**
 * ADR-0012 §6 + SPEC-006 — the `alerts` table (Detection MVP, Postgres-only).
 * Alerts are mutable triage state (status, assignment, timestamps), which is why
 * they live in Postgres and not in append-only ClickHouse (ADR-0012 §6, amending
 * ADR-0003 §Retention). Idempotent (MUST-2), applied after 0001_initial.
 *
 * `alert_id` has NO default: the detection slice generates a UUIDv7 (Phase-5 5e),
 * not the DB a v4. `source_events` is `uuid[]` (version-agnostic); the alert.json
 * source_events UUID-pattern relaxation lands with the persist step (5e). CHECK
 * constraints encode alert.json's allOf conditionals (rule_id/model_id), the
 * cg_score.json 0..1 range + its anyOf (>=1 score present), and source_events
 * cardinality. The status enum is a CHECK (not a pg TYPE) for fidelity to
 * ADR-0012 §6 and because the domain may grow (ALTER of a CHECK is trivial).
 */
export async function up(db: Kysely<unknown>): Promise<void> {
  await sql`
    CREATE TABLE IF NOT EXISTS alerts (
      alert_id            uuid        PRIMARY KEY,                 -- UUIDv7, generated by the detection slice (5e); no DB default
      org_id              text        NOT NULL DEFAULT 'default',
      agent_id            uuid        NOT NULL REFERENCES agents (agent_id),
      category_uid        smallint    NOT NULL DEFAULT 10,
      class_uid           integer     NOT NULL DEFAULT 10001,      -- CGES Alert
      activity_id         smallint    NOT NULL DEFAULT 1,          -- 1 = Created
      cg_kind             text        NOT NULL DEFAULT 'alert',
      title               text        NOT NULL,
      description         text,
      severity_id         smallint    NOT NULL,                    -- OCSF severity (common/ocsf_severity.json)
      cg_detection_source text        NOT NULL
                            CHECK (cg_detection_source IN ('rule', 'ml', 'hybrid')),
      rule_id             text,
      model_id            text,
      source_events       uuid[]      NOT NULL,                    -- >= 1 cges_events.event_id; version-agnostic (pattern relax is 5e)
      heuristic_score     numeric(4,3),
      ueba_score          numeric(4,3),
      ml_score            numeric(4,3),
      final_score         numeric(4,3) NOT NULL,                   -- renormalized per ADR-0012 §4
      cg_mitre            jsonb,                                   -- { tactics: [], techniques: [] }
      dedup_key           text        NOT NULL,
      status              text        NOT NULL DEFAULT 'new'
                            CHECK (status IN ('new', 'acknowledged', 'resolved', 'false_positive')),
      created_at          timestamptz NOT NULL DEFAULT now(),
      updated_at          timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT alerts_dedup_key_unique       UNIQUE (dedup_key),
      CONSTRAINT alerts_rule_id_present        CHECK (cg_detection_source NOT IN ('rule','hybrid') OR rule_id  IS NOT NULL),
      CONSTRAINT alerts_model_id_present       CHECK (cg_detection_source NOT IN ('ml','hybrid')   OR model_id IS NOT NULL),
      CONSTRAINT alerts_source_events_nonempty CHECK (cardinality(source_events) >= 1),
      CONSTRAINT alerts_final_score_range      CHECK (final_score BETWEEN 0 AND 1),
      CONSTRAINT alerts_severity_range         CHECK (severity_id BETWEEN 0 AND 6),  -- hardening per ocsf_severity.json (beyond ADR-0012 §6)
      CONSTRAINT alerts_heuristic_range        CHECK (heuristic_score IS NULL OR heuristic_score BETWEEN 0 AND 1),
      CONSTRAINT alerts_ueba_range             CHECK (ueba_score IS NULL OR ueba_score BETWEEN 0 AND 1),
      CONSTRAINT alerts_ml_range               CHECK (ml_score IS NULL OR ml_score BETWEEN 0 AND 1),
      CONSTRAINT alerts_score_present          CHECK (num_nonnulls(heuristic_score, ueba_score, ml_score) >= 1)
    )
  `.execute(db);
}

export async function down(db: Kysely<unknown>): Promise<void> {
  await sql`DROP TABLE IF EXISTS alerts`.execute(db);
}
